### PR TITLE
[DNM] Test percona arm build on openlab

### PR DESCRIPTION
**Pull request by wangxiyuan**
This PR is  a demo for percona-server arm build test on OpenLab.

### CODE REVIEW

**Comment by wangxiyuan** [comment]
recheck

**Comment by wangxiyuan** [comment]
recheck

**Comment by wangxiyuan** [comment]
recheck

**Comment by wangxiyuan** [comment]
recheck

**Comment by wangxiyuan** [comment]
recheck

**Comment by wangxiyuan** [comment]
recheck

**Comment by wangxiyuan** [comment]
recheck

**Comment by wangxiyuan** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by wangxiyuan** [comment]
recheck

**Comment by wangxiyuan** [comment]
recheck

**Comment by wangxiyuan** [comment]
recheck

**Comment by wangxiyuan** [comment]
recheck

**Pull request merged**
